### ISSUE TITLE
Add scrollbar to feature list

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#100]
Currently the feature lists is expanding and breaking the UI eventually. A scroll bar and a fixed height will solve this problem.

**Comment by FRosner** [comment]
QA: Add more features than the list can display. A scroll bar should appear. Adding and removing features should work as before.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 898f24edd4709c0628f778adf6f792efa6384b4c
Built on: 2013-09-18 22:08:44
