### ISSUE TITLE
Make GUI resizable

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#103]
The GUI should be resizable and the layout should not look that bad after resizing. Also it should not be possible to destroy the layout by choosing a size that is too small.

**Comment by FRosner** [comment]
We have to make sure that all components added in the future or other changes made to the GUI keep it resizable.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-24 12:05:43
