### ISSUE TITLE
Export file chooser tests not platform independent

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#105]
The file chooser is currently tested using a robot that presses tab and enter to select the confirmation button. On other operating systems this does not work as the file chooser dialog is system dependent. The tests should be reworked in order to be platform independent. 

The file must be selected using the GUI test util class and confirmation must happen on this way as well.

QA: Please test in Linux and Mac environment.

**Comment by FRosner** [comment]
@Bantolomeus please verify one of the common Linux distributions (Ubuntu, Debian, Fedora, SUSE, ...).

I will verify if DataGenerator can be built on MacOS.

**Comment by FRosner** [comment]
Verified on MacOS.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 62ed463
Built on: 2013-09-18 17:42:28

**Comment by Bantolomeus** [comment]
Verified on Ubuntu 10.04.4.

Data Generator
Version:0.2.2
Revision: 11e77603b8888047fac5ee912a343cac8407b498
Built on: 2013-10-12 14:33:22
