### ISSUE TITLE
Mvn package failure

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#106]
I used the command "mvn package" in the git bash console an then I got this error massage (16.9.2013 / 16:54):
![error](https://f.cloud.github.com/assets/1318613/1149746/156f9aca-1ee0-11e3-9d99-e81145ddfabd.JPG)

**Comment by FRosner** [comment]
@Bantolomeus did you try `mvn clean`? There are some test failures in the GUI tests currently, if your computer is too slow. But the NoSuchMethodError is strange. Please tell me if `mvn clean` solves the problem.

**Comment by FRosner** [comment]
@Bantolomeus you also seem to have more tests than I do. Did you pull the latest version?

**Comment by Bantolomeus** [comment]
@FRosner I was in the master branch und pulled the project. I didnt tried `mvn clean`.

@FRosner I was in the master branch and pulled the project. I didn't try `mvn clean`.

**Comment by Bantolomeus** [comment]
@FRosner After I used `mvn clean` and then `mvn package` the build was a sucess.

@FRosner After I used `mvn clean` and then `mvn package` the build was a success.
