### ISSUE TITLE
"testTabbing" fails

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#107]
I used the command `mvn clear` and then `mvn package`. I was in the master branch. 18.9. 15:25
That is the result:
![error1](https://f.cloud.github.com/assets/1318613/1165064/7c58085e-2065-11e3-92cb-06ac7254d743.JPG)

**Comment by FRosner** [comment]
Did you do `git pull`? I tried to fix that problem yesterday. If it is not fixed, please let me know.

----- Original Message -----

**Comment by FRosner** [comment]
The problem is that the robot presses the tab key and the tests wants to see the focus changes. If your PC is too slow the test will fail because the delay after pressing tab is too small. Maybe I should increase it further...

**Comment by FRosner** [comment]
I reopened #104 for this. Please let me know if it is fixed.
