### ISSUE TITLE
Make resizing look good

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#114]
After resizing the marked fields are too high. 
![resize](https://f.cloud.github.com/assets/1318613/1199019/fb5e1196-2503-11e3-9a02-8a9f395407d0.JPG)

**Comment by FRosner** [comment]
@Bantolomeus what behaviour would you expect?

**Comment by FRosner** [comment]
Done. Needs to be merged to master after v0.2.1 is branched.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.2
Revision: 11e77603b8888047fac5ee912a343cac8407b498
Built on: 2013-10-11 14:24:52
