### ISSUE TITLE
Expand preview table if number of features is bigger than 4

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#115]
The preview table model should increase the number of columns if more feature definitions get added. Currently the preview is limited to 4 feature defintions.

Either a scrollbar should be added or the column width should be decreased.

---

Depends on: #36

**Comment by FRosner** [comment]
I should add some out of bounds exceptions when the model access index is invalid.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.2
Revision: 11e77603b8888047fac5ee912a343cac8407b498
Built on: 2013-10-11 14:24:52
