### ISSUE TITLE
Create separate dialog for adding feature definitions

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#118]
Like sketched in #44 there should be a dialog for adding feature definitions.

**Comment by FRosner** [comment]
@Bantolomeus in order to test please try to add some features using the new dialog. Everything should work as before but the fact that it requires a click more :)

**Comment by Bantolomeus** [comment]
I found a bug. Sometimes you can not close the Feature dialog.
How to reproduce:
1.) press Add Feature
2.) choose Uniform Categorial
3.) #States = 1001
4.) press OK
5.) press Abbrechen
6.) press Add Feature
7.) press Abbrechen

If you only press Abbrechen the window won´t close (can be pressed multiple times).
If you only press OK the window won´t close (can be pressed multiple times).
If you press OK and then Abbrechen it will close.

**Comment by FRosner** [comment]
Fixed.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.3
Revision: 5ca852a704df23eaab8a7fd2db895a1ecd356f9a
Built on: 2013-11-07 20:12:49
