### ISSUE TITLE
Add button and dialog for editing features

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#119]
See #44 for a sketch.

**Comment by FRosner** [comment]
I need to update the feature definition dialog with the selected parameters.

**Comment by Bantolomeus** [comment]
@FRosner I do not know what you mean with dialog or where it is. 
Can you please explain it to me?

**Comment by FRosner** [comment]
@Bantolomeus when you click on "Edit Feature", a dialog window should appear. It most certainly looks the same as the "Add Feature" window.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.4
Revision: 8a13921d2f2687dbfd5a80f6a4a80d73843594f8
Built on: 2013-11-30 11:12:54
