### ISSUE TITLE
Implement CSV export connection

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#13]
Every connection must implement the export connection interface (see #12). Best is to buffer some instances before writing to file. When constructing the CSV export connection, the file to export to should be passed as an argument.

**Comment by FRosner** [comment]
@Husterknupp Please write a new class in the export package that is implementing the ExportConnection inferface. Please do test first. If you need any help with Git, please let me now.

For now it should be better to actually pass an output stream to export to instead of a file when invoking the constructor. This way we are able to export to the standard output stream as well (as requested in #15).

For writing on the output stream you can simply use a BufferedWriter. Don't forget to close the output stream after the connection's close method has been called.

In order to unit test the connection you should [mock](http://en.wikipedia.org/wiki/Mock_object) the output stream and verify it afterwards. As I did not include a mocking framework for now, you have to write your own mock connection. Maybe you can have a look at the MockedExportConnection which does the same thing but one layer above (for testing the generator independently of the connection implementation). If you need something, feel free to ask :)

**Comment by FRosner** [comment]
@Husterknupp I cherry picked the commits of #20 into branch v0.1. You are now able to use Mockito and don't have to write your own mocks. See [a69e635 (DataGeneratorTest)](https://github.com/FRosner/DataGenerator/commit/a69e635490e4ad8c436dd1e83e3fc8eec3df179c) and [Mockito - How to drink it?](http://code.google.com/p/mockito/) for a simple example how to verify method calls.

If you need anything, just let me know. I hope this simplifies your work.

**Comment by Husterknupp** [comment]
@FRosner please do not forget to refactor DummyFeatureValue
