### ISSUE TITLE
Check licenses of packaged libraries

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#139]
I noticed that there are recursive dependencies like `jfreechart-1.0.13`. I must check that none of them are incompatible with my license. I'm not sure whether I need all of them anyway.

**Comment by Husterknupp** [comment]
Created a [wiki page](https://github.com/FRosner/DataGenerator/wiki/License-Accordance) with a detailed accordance check.

**Comment by Husterknupp** [comment]
@FRosner I am considering some verses in §§2 and 3 of the [LGPL](http://www.gnu.org/licenses/lgpl.html) and have two issues:
1. It is said there, that we have to highlight every case, where we use header code from the LGPL libraries is not only by passing arguments but by actually modifying the code itself. Is that the case with code from jfreechart and jcommon? Using the methods with passed arguments is nearly free to use.
2. I probably misled you in our last conversation about LGPL. I now understood, that we have to leave every library that is under the LGPL free to modify for the end user. But in contrast to the GPL we are not forced to open our own source code. Is this a problem?

**Comment by FRosner** [comment]
Please create a wiki page with all packaged libraries and their licenses. Distinguish between direct dependencies and transitive ones.
1. I am not sure whether I get your point. I think that the libraries are just used by libraries we use.
2. As we open the source code and do not modify the libraries I guess there should be no problem. Maybe we can talk to a lawyer. Do you know someone?
