### ISSUE TITLE
Standard file ending is not .csv

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#140]
If you create a new export file and do not give it a ending, then it won´t have a ending.
In the last release (0.2.1) the standard ending was .csv.

Look at issue #90 .

![nostandartfileending](https://f.cloud.github.com/assets/1318613/1292692/38193aca-3058-11e3-8a86-cb215143e49f.JPG)

Is this behavior because of issue #137 ?

---

Data Generator
Version: 0.2.2
Revision: 92f394aedacb219253a1552287887b070478526f
Built on: 2013-10-08 22:10:07

**Comment by FRosner** [comment]
@Bantolomeus which file type did you select?

**Comment by Bantolomeus** [comment]
@FRosner Any File (*)

**Comment by FRosner** [comment]
@Bantolomeus That is why no ending is added. You need to select CSV in order to make the file chooser add an ending. This is because it should be possible for the user to select the ending he wants by choosing "Any File (*)". Or do you expect the file chooser to add .csv if you want to save it to any file type?

PS: #137 is only a precondition backend thing. It has nothing to do with anything you will ever notice.

**Comment by Bantolomeus** [comment]
@FRosner Hm, true. But I was expecting, that there should be an ending.
Maybe only if there is no ending it should add the csv ending (if All Files is selected) or would someone really want to create a file with no ending?

**Comment by FRosner** [comment]
@Bantolomeus So what is your suggestion? The ticket description indicates that you expect CSV to be the default filter selected. I double checked it right now and this seems to be the case. If the user does not change the filter .csv will be added.

However it would be a nice thing to communicate that right now actually only CSV can be exported. The GUI does not document this in any way. I will create a follow up ticket for this.

**Comment by Bantolomeus** [comment]
If you build the DataGenerator with Maven, then the Standard file filter is Any File(*). Default should be CSV.
Please fix it.

**Comment by FRosner** [comment]
Should be fine now.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.2
Revision: 11e77603b8888047fac5ee912a343cac8407b498
Built on: 2013-10-08 23:21:27
