### ISSUE TITLE
Preview table labeling

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#143]
Maybe it wouldn´t be wrong to add a preview table labeling.
I do not know where or how exactly but maybe somewhere in the marked area.

![featurename](https://f.cloud.github.com/assets/1318613/1314351/d8866418-3271-11e3-905c-5808493a4197.JPG)

**Comment by FRosner** [comment]
What is a table label? Does this duplicate #131?

**Comment by Bantolomeus** [comment]
Excuse me. Yes it duplicate #131.
