### ISSUE TITLE
Supply methods for calculating mean and variance in StatisticsUtil

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#147]
Currently our distribution unit tests calculate the needed moments on their own. It would be nice to have methods supplied by some utility classes in order to make the code more readable.

**Comment by FRosner** [comment]
@Husterknupp please assign the ticket to you and choose a milestone / talk to me before committing anything to master. Best way would be to keep a feature branch and merge it when it's done and I set the version.

**Comment by Husterknupp** [comment]
@FRosner sorry for that. I will do so with future issues.
