### ISSUE TITLE
Test capability of feature value's equals

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#148]
We must test that `equals()` of both discrete and continuous feature values is capable of a class which is not of the same type.

**Comment by FRosner** [comment]
@Husterknupp do it.

**Comment by FRosner** [comment]
@Husterknupp what is your status? I plan to stop development for v0.3 on Sunday. I think this one in particular is not that complicated. Will you make it by Sunday?

**Comment by Husterknupp** [comment]
@FRosner I am not ready, yet. But I will finish before Sunday.

**Comment by FRosner** [comment]
@Husterknupp alright. Let me know if you have any troubles.
