### ISSUE TITLE
Limit number of states (Categorial Distribution)

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#158]
Choosing too many states results in too small probability values and too big arrays (possibly out of memory). There should be some reasonable limit (maybe 100?). No exceptions or errors should occur no matter what allowed value is chosen.

**Comment by FRosner** [comment]
Limited to 1000.

**Comment by Bantolomeus** [comment]
Verified. 

Data Generator
Version: 0.3
Revision: 24d321693c901fac7baab3144ce183741f4d402a
Built on: 2013-11-05 20:45:56
