### ISSUE TITLE
Add more options to the menu bar

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#162]
Options:
- Close DataGenerator
- Add Feature
- Generate Data

**Comment by FRosner** [comment]
@Husterknupp please add a new menu item called "File" that contains the close option. I'd like to see a "Features" item for manipulating the feature list and a "Data Generation", "Generation" or "Export" item for choosing export formats (later) and starting generation.

Suggestions for different names are welcome.

**Comment by Husterknupp** [comment]
@FRosner I like your names. Only considered the generate data function to be accessed by the "File" menu. Since the file menu often holds the main functions and the generate data function is our main function (at least according to the software name) it might be better placed there. The third menu then should be called "Export"/"Export as ...". 
What do you say?

**Comment by FRosner** [comment]
Steven Jobs did not want you to put random smileys in our program. If you want to improve the user experience you have to do it in a more subtle manner. Please remove the smiley and the "- Data Generator" stuff and think of a better (subtle) way. I spoke to several people and they all think that this is too much.

**Comment by FRosner** [comment]
@Husterknupp maybe you can design a logo for the data generator. I think that this is a first step in your (the right) direction. I opened #174 for this.

**Comment by Bantolomeus** [comment]
@Husterknupp I found a bug.
How to reproduce:
1. add a valide Bernoulli Feature 
2. edit the Bernoulli Feature and set P = 15 and press OK
3. close the Feature with Abbrechen
4. edit it again and the Distribution Parameter background is still red.

Please rework the background color. The background should not be red if you open a Feature.

**Comment by Husterknupp** [comment]
@Bantolomeus why do you think, this problem belongs to the issue of adding more options to the menu bar? I opened a new ticket for that #178.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.4
Revision: 8a13921d2f2687dbfd5a80f6a4a80d73843594f8
Built on: 2013-11-30 11:12:54
