### ISSUE TITLE
Design icon

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#174]
In order to attract more users we should design a logo. The logo should be a vector graphics or at least have a high resolution so we can generate different sizes easily (thumbnail, icon, full size).

Drafts should be attached here.

**Comment by FRosner** [comment]
@Husterknupp please attach some screenshots here.

**Comment by FRosner** [comment]
@Husterknupp I may have found someone to help us. I will assign that ticket back to me for now.

**Comment by FRosner** [comment]
![unbenannt](https://f.cloud.github.com/assets/3427394/1748564/aadd201e-64c7-11e3-90a6-403a95a42114.PNG)

**Comment by FRosner** [comment]
@Husterknupp what do you think?

**Comment by FRosner** [comment]
![unbenannt](https://f.cloud.github.com/assets/3427394/1748575/71c773be-64c8-11e3-9642-89494fe465eb.PNG)

**Comment by Husterknupp** [comment]
@FRosner  @Bantolomeus This is how the DG looks with the black cube as icon. The white frame around the icon should be removed, but what do you think beside that?
![unbenannt](https://f.cloud.github.com/assets/1265382/2043599/ac615886-89e0-11e3-921d-e88e90905851.JPG)

**Comment by FRosner** [comment]
We'll have the blue dice.
