### ISSUE TITLE
Fix background color of text field

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#178]
The Add Feature dialog somehow remembers what I put in the text forms the time I opened the dialog before. In case I tried to enter some invalid data, abort the entry and reopen the dialog with the Edit Feature button the text field is marked as invalid where it should not be.
![unbenannt](https://f.cloud.github.com/assets/1265382/1580336/1715780a-51bb-11e3-87a1-c1f7ed119512.JPG)

**Comment by FRosner** [comment]
My suggestion: validate parameters not only when pressing "OK" but also when pressing "Cancel". However, the dialog should close no matter what if the user presses "Cancel". "OK" should still check the validation.

**Comment by Husterknupp** [comment]
@FRosner I am a little bit confused how to write the test for this functionality. My approach would be to let a Robot click the `CANCEL_OPTION` of the `feauteDefinitionDialog`. But how can I get access to the dialog object?
First I wanted to omit the test because I thought the already existing validation test would be enough. But isn't it worth testing when now canceling should also verify?

**Comment by FRosner** [comment]
Yes I believe it is worth it. Shouldn't existing tests fail? The method `tryToAddSelectedFeatureAndGiveUp()` of the Swing menu test util is used to abort the dialog. However after aborting it is asserted that the fields are red. We should talk about this tomorrow or friday.

**Comment by FRosner** [comment]
@Husterknupp do we have tests for both verifying added and edited feature definitions?

**Comment by Husterknupp** [comment]
@FRosner currently, we are verifying the components only when the `addFeatureButton` was clicked. We don't test it with the `editFeatureButton`. But as far as the listener is capsuled in the `featureDefinitionDialog`, thus is one and the same for both editing and adding features, i'm not quite sure where it would be helpful to test the verification twice.

**Comment by FRosner** [comment]
@Husterknupp those tests are useful as integration tests, yes. Integration tests should imitate common workflows and check whether they are correct, intependently of the implementation.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.4
Revision: 8a13921d2f2687dbfd5a80f6a4a80d73843594f8
Built on: 2013-11-30 11:12:54
