### ISSUE TITLE
Consider having an "Add Dependency" button

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#210]
We would be perfectly fine to display the dialog in #208 when adding a feature. The user would be able to decide ad hoc if he wants any conditional parameters that would make that feature a dependent one.

@Husterknupp @Bantolomeus any strong opinions against removing the "Add Dependency" button again?

**Comment by Bantolomeus** [comment]
No complain here

**Comment by Husterknupp** [comment]
I do not think that we need this button, now. Even adding dependencies after having add a certain feature is possible without the button.

Probably after releasing the alpha, if any users seem to be missing this way of adding dependencies - probably then we might rethink this issue.

**Comment by FRosner** [comment]
Alright. I am going to remove it then.
