### ISSUE TITLE
Include option to print feature names as CSV header

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#24]
Exported data should contain feature definitions (at least the feature names) as well.

**Comment by FRosner** [comment]
@Husterknupp can you please implement the backend stuff for this option? You could add a boolean to the constructor of the CSV export connection that indicates whether the feature names will be printed in the first row of the CSV.

Please reassign the ticket to me if I can start working on the frontend option.

**Comment by Husterknupp** [comment]
@FRosner can you please help me? I do not find a way to access the names of the given feature definitions out of the export connection, to be more specific out of an instance.

**Comment by FRosner** [comment]
@Husterknupp Yeah that is because currently there is no way to access feature definitions via the instances. We need to hand it to the export connection on some other way.

Possible solution: Add a method to the export connection interface that takes feature definitions and does something with it if necessary, like print a CSV header or create a data base schema. Maybe call it like exportFeatureDefinitions or exportMetaData. It then has to be called by the data generator initially before exporting instances.

**Comment by FRosner** [comment]
I can't compile. Did you try `mvn test`? It seems that you added production code to test packages. This will not work as maven ignores test classes when packaging.

**Comment by FRosner** [comment]
Fixed that.

**Comment by FRosner** [comment]
Tests for the DataGenerator are missing. I created a followup ticket (#127) because the ExportConnection API changed in v0.2.2 which makes the testing different.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1
Revision: c8aee7a96f9fd17dfb22781122720c07bf21dc95
Built on: 2013-10-04 21:01:36
