### ISSUE TITLE
Provide option to include instance ID to CSV export

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#28]
The row count should simply be the instance ID.

**Comment by FRosner** [comment]
@Husterknupp can you please implement the backend stuff for this option? You could add a boolean to the constructor of the CSV export connection that indicates whether the instance id should be printed in the first column of the exported CSV.

Please reassign the ticket to me if I can start working on the frontend option.

**Comment by FRosner** [comment]
Some tests still missing. #127 is a follow-up ticket for this issue.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1
Revision: c8aee7a96f9fd17dfb22781122720c07bf21dc95
Built on: 2013-10-04 21:01:36
