### ISSUE TITLE
Write DataGeneratorIntegrationTest

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#32]
We must test the correct interaction of all components used by the DataGenerator in a production environment (no mocks, no dummies).

The test should verify that all the following steps are done correctly:
- create some feature definitions with gaussian distributions
- create a CSV export connection that exports to a ByteArrayOutputStream
- create a data generator with a bigger number of instances
- generate data
- verify output (correct format, numbers actually continuous)

**Comment by Husterknupp** [comment]
I'm verifying the output via regex-matching ("number, dot, number, comma" and so on) for the first and the last line.

**Comment by FRosner** [comment]
@Husterknupp That's a good idea. You could also use Double.parseDouble() and catch a possibly occuring NumberFormatException. This is not good practice to test string formatting in production but as this is test code it would be ok for me as well :)

---

Mind that if you are testing a matching regex very often in production code it is better to compile the pattern one time and only use the matcher instead of using String.matches() over and over again.
