### ISSUE TITLE
Introduce table view with preview data

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#36]
There should be some kind of preview area. This will help understanding the output before actually generating a huge data file.

The preview table should include at least the feature names and some random samples. It should be updated whenever the feature definitions are modified.

**Comment by FRosner** [comment]
I need to wait for the changes from #24 to gain access to the feature names in order to print them in the preview table.

**Comment by FRosner** [comment]
PreviewTableManagerTest missing. I will implement this in #129.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.2
Revision: 11e77603b8888047fac5ee912a343cac8407b498
Built on: 2013-10-11 14:24:52
