### ISSUE TITLE
Build v0.2 and publish it

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#52]

**Comment by FRosner** [comment]
I must not forget to change the main to the swing launcher in the manifest.

**Comment by FRosner** [comment]
@Bantolomeus Please checkout branch v0.2 (`git checkout v0.2`) and test everything. If you find something, create an issue (or ask me first if you are not sure).

**Comment by Bantolomeus** [comment]
@FRosner Please fix the artifact name (remove "SNAPSHOT").

**Comment by Bantolomeus** [comment]
@FRosner  What does NaN in the result file stand for? Not a number? Is it right that there stand sometimes NaN and other times infinity? And is it possible that the result can be one time infinity and the next time -infinity?
![nanminusinfinity](https://f.cloud.github.com/assets/1318613/1119991/0fd16276-1a8d-11e3-99c0-79043e8de5da.JPG)

**Comment by FRosner** [comment]
@Bantolomeus You probably entered a number that is too large for Java to handle. We should limit the number using the verifiers. Good find! I will create a ticket for this.

We have tickets for everything you found during QA. I put them in version v0.2.1 as none of them is critical. If there is nothing else you'd like to criticize we can tag branch v0.2 and release it.

**Comment by Bantolomeus** [comment]
@FRosner I don´t want to criticize any more. You can release it.
