### ISSUE TITLE
Add VisibleForTesting annotation

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#61]
Write a new annotation class called VisibleForTesting that can be added to private members or getters of private members that have been made package private in order to be accessable by tests.

The DataGeneratorService has some of these methods and this needs to be documented. Please add the annotation to them as well.

**Comment by Husterknupp** [comment]
@FRosner can I close this issue?

**Comment by FRosner** [comment]
@Husterknupp I reviewed and commented your commit. After fixing the commit you may close the issue. :+1:

**Comment by FRosner** [comment]
# Do NOT amend shared commits.
