### ISSUE TITLE
Set up Eclipse on your computer

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#7]
Import project into Eclipse and configure your workspace.

Configuration:
- adjust line wrapping to 120
- activate editor save actions
  - format all lines
  - organize imports
  - additional actions: add missing override annotiations, add missing deprecated annotations, remove unnecessary casts

**Comment by Husterknupp** [comment]
@FRosner I'm not sure, whether this is the right config: ![m2_repo](https://f.cloud.github.com/assets/1265382/1046413/43c87ae8-103c-11e3-8edd-b02615d533c0.JPG)

I found it on Google (not the picture - this is my screenshot - but the way to get there). Can I close the issue?

**Comment by FRosner** [comment]
@Husterknupp This is the right way to set up your Maven repository in Eclipse. Before closing the issue please make sure that you adjusted the other configuration concerning the Java editor and code formatter (see issue description) as well.
