### ISSUE TITLE
Missing dependency fest.swing in packaged jar

### ISSUE THREAD

**Issue by Husterknupp** [FRosner/DataGenerator#74]
![image](https://f.cloud.github.com/assets/1265382/1106401/726d5fb6-1943-11e3-844f-9d1be304e829.png)

**Comment by FRosner** [comment]
I removed the test scope from the fest-swing dependency for now. Sooner or later we should move the TestUtils from SwingMenu to some extra class in the test package. I will create a follow-up ticket for that.
