### ISSUE TITLE
Not well readable letters

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#80]
In the Name field and in the export file field are not all letters fine readable.

![cutted](https://f.cloud.github.com/assets/1318613/1120019/675b2ab2-1a8e-11e3-9eb5-41e4262daa99.JPG)
![notreadable](https://f.cloud.github.com/assets/1318613/1120172/cb181a82-1a94-11e3-9be5-05e39e6c26dd.JPG)

**Comment by FRosner** [comment]
We should consider either increasing the height of the input fields or decreasing the font size.

**Comment by FRosner** [comment]
I increased the height of all input fields.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-26 22:18:24
