### ISSUE TITLE
Too long feature name causes issues: limit required

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#82]
@FRosner The name in the Name field (in the running DataGenerator) shouldn´t be allowed to be to long. If the name is to long (was over 100000 characters long) it lags very much and create stripes (look at screenshot)
![long name](https://f.cloud.github.com/assets/1318613/1119887/23d06780-1a89-11e3-822a-5b360be985e3.JPG)

**Comment by FRosner** [comment]
We should limit the characters in the input field. I think 25 characters are sufficient. Either we limit the input while typing or we use the InputVerifiers.

See #87 for the ticket concerning the limitation of number fields.

**Comment by FRosner** [comment]
Limited the feature name to 30 characters.

**Comment by Bantolomeus** [comment]
Verified.
