### ISSUE TITLE
Prevent multiple generation threads

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#85]
A user must not be able to click the generate button twice unless the generation has finished. The DataGeneratorService must start another generation process if one is in progress.

See #83.

**Comment by Bantolomeus** [comment]
I cannot press "generate data" before the generation process is finished. (solved)
I can open the DataGenerator two times and write into the same file:
![doublegenerator](https://f.cloud.github.com/assets/1318613/1140967/be0d944a-1ca9-11e3-9417-931fbbc68810.JPG)

**Comment by FRosner** [comment]
Ok. I should probably display some kind of warning message when the file exists. Please open another ticket for this.

**Comment by Bantolomeus** [comment]
Verified.
