### ISSUE TITLE
Introduce new button: "Abort Generation"

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#86]
There should be a button to abort the generation if too many instances have been chosen accidently. The DataGeneratorService must know if there is a generation in progress.

---

Related to: #85

**Comment by FRosner** [comment]
I should add GUI tests actually generating data and testing the abortion as well.

**Comment by FRosner** [comment]
@Bantolomeus you can already test the functionality manually if you want. I implemented everything necessary. Just remove the QA required flag and leave a short comment after verification. I will close the ticket as soon as I finished the automated tests.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-26 22:18:24
