### ISSUE TITLE
Limit the amount of characters in the input fields for numbers

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#87]
It should not be possible to enter values in fields like distribution parameters or number of instances that are parsed to Infinity or NaN.

I should include this into the reworked InputVerifiers.

---

Depends on: #78

**Comment by FRosner** [comment]
@Bantolomeus How to test: Enter really huge numbers into the input fields where numbers should be entered and check whether they are still valid.

**Comment by Bantolomeus** [comment]
Verified.
