### ISSUE TITLE
Export file ending should reflect the currently selected export type

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#90]
I can choose every ending I want for the file. Shouldn´t be allowed. Only allow [file name].csv
![ending](https://f.cloud.github.com/assets/1318613/1128610/454dce52-1b6f-11e3-91a4-6e1db114ecce.JPG)
![ending2](https://f.cloud.github.com/assets/1318613/1128624/7d6e6832-1b6f-11e3-84a9-63b5dca5e572.JPG)

**Comment by Husterknupp** [comment]
We should consider implementing a white list for allowed file endings, e. g. .csv, .tsv, ...

**Comment by FRosner** [comment]
Why would you want to do this? This is typical for windows users. A file type is not determined by its ending. The ending is optional to help the user or operating systems like Windows associating programs with the file type.

However I agree with you that the filechooser should reflect the currently selected type. That is by choosing CSV export type and entering a file name like "test" it should export to "test.csv". Whitelisting allowed endings is not what I want to have.

**Comment by Husterknupp** [comment]
Thanks for the advice :+1: Hence, should it refer to the chosen export format, so the user is not allowed to even edit the file ending?

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-26 22:18:24
