### ISSUE TITLE
Export file chooser should remember the last selected folder

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#92]
It would be nice if the export file chooser would remember the last selected folder.

**Comment by FRosner** [comment]
@Bantolomeus The file chooser seems to remember the last selected directory as long as the program is running. After restarting it is not, of course, as we do not persist any changes. So what was this ticket about?

However it would still be nice to have the directory containing the jar as the standard directory. I created #108 for this issue.

**Comment by Bantolomeus** [comment]
You understanded the ticket. And I can not see the problem either. I just tested it.

Verified.

You understood the ticket. And I can not see the problem either. I just tested it.

Verified.
