### ISSUE TITLE
Warning message if file already exist

### ISSUE THREAD

**Issue by Bantolomeus** [FRosner/DataGenerator#94]
Display a warning message if the selected export file already exist.

**Comment by FRosner** [comment]
I should take a look at http://stackoverflow.com/questions/3651494/jfilechooser-with-confirmation-dialog

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-24 12:05:43
