### ISSUE TITLE
Test frame should be closed after each test case

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#95]
Each GUI test spawns a new swing menu (test frame). It should be destroyed in a `@After` annotated method to avoid having too many swing menues open when more tests get added.

![too_many_windows](https://f.cloud.github.com/assets/3427394/1141685/5d978ebc-1cb9-11e3-937f-56e77d62a223.png)

**Comment by FRosner** [comment]
@Husterknupp If you need advice, take a look at the `OrderedFocusTraversalPolicyTest`.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1
Revision: c8aee7a96f9fd17dfb22781122720c07bf21dc95
Built on: 2013-10-04 21:01:36
