### ISSUE TITLE
Include artifact meta data into the GUI

### ISSUE THREAD

**Issue by FRosner** [FRosner/DataGenerator#97]
There should be a "about" button displaying the application meta data stored in the artifact.

---

Depends on: #96

**Comment by FRosner** [comment]
Application meta data cannot be copied in the message dialog. I should include a text area to copy it from for QA tasks.

**Comment by Bantolomeus** [comment]
Verified.

Data Generator
Version: 0.2.1-SNAPSHOT
Revision: 04dd8afb8c1b80973ed1c5953819360fd8b56ef6
Built on: 2013-09-26 22:18:24
